# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '2'

# Define services
services:
  # App backend service
  moe-database:
    container_name: moe-database
    image: mysql/mysql-server:5.7
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_DATABASE: moe_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
#    networks:
#      vpcbr:
#        ipv4_address: 172.50.0.30
  api-server:
    restart: always
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run -Pdocker
    depends_on:
      - moe-database
  moe-nginx:
    container_name: moe-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api-server

volumes:
  db-data: